# Data Settings
DataRoot: /mnt/data/yuanfang/DC-MT-SRC/DATA/ISIC2018/
Data_CLASSES: ['MEL','NV','BCC','AKIEC','BKL','DF','VASC']
TrainFold: ./core/data/train_index.csv
ValidFold: ./core/data/val_index.csv
TestFold: ./core/data/test_index.csv
base_dir_prev: DC_MT_GCN
description: DC_MT_GCN
student_model_path: /mnt/data/yuanfang/DC-MT-SRC/outputs/DC_MT_000-DC_MT/checkpoint/S_fold[0]_se_resnext50_32x4d/S_fold[0]_se_resnext50_32x4d_best_acc.pth
teacher_model_path: /mnt/data/yuanfang/DC-MT-SRC/outputs/DC_MT_000-DC_MT/checkpoint/T_fold[0]_se_resnext50_32x4d/T_fold[0]_se_resnext50_32x4d_best_acc.pth
gcn_model_path: /mnt/data/yuanfang/DC-MT-SRC/outputs/GCN_001-onlyGCN/checkpoint/G_fold[0]_se_resnext50_32x4d/G_fold[0]_se_resnext50_32x4d_best_acc.pth

# Gcn Settings
gcn_start_epoch: 20
gcn_feature_dim: 1024
gcn_hidden_dim: 256
gcn_hidden_num: 2
gcn_dropout: 0

# Training Settings
consistency_start_epoch: 0
gcn_weight: 1.0
src_weight: 0
attention_weight: 1.0

deterministic: True
seed: 6081
n_fold: 10
label_fold: [0]
GPUs: [3]
num_workers: 8
batchsize: 80
label_bs: 20
ema_decay: 0.999

# Visulization Settings
display_freq: 10
display_ncols: 2
display_id: 1
display_winsize: 256
display_server: http://localhost
display_port: 8097
display_env: main
update_html_freq: 100

# Optimizer settings
optim: Adam
lr: 0.00001
momentum: 0.9
nesterov: False
weight_decay: 0.00005

# Model Settings
arch: se_resnext50_32x4d
Using_pretrained_weights: True
in_channels: 3
img_size: 256
lr_decay_freq: 10
lr_decay: 0.8
num_epoch: 20
print_freq: 20
valid_freq: 1
save_model_freq: 1
SaveFolderName: 'mean_teacher'
Cls:
  resume:

### Consistency Loss settings
consistency_cls: 5
consistency_att: 1
consistency_rampup: 50

